command_timeout_seconds: 20
command_allowlist:
  - echo
  - ls
  - pwd
  - cat
  - grep
  - find
isolation:
  run_as_non_root: true
  network_access: constrained
  host_filesystem_access: denied_by_default
